version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proctor_app
    ports:
      - "8080:8080"
    environment:
      DB_PASSWORD: strongpass
    depends_on:
      - db
    networks:
      - proctor-system
    restart: always

  db:
    image: postgres
    container_name: proctor_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: proctor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strongpass
    volumes:
      - proctor_db_data:/var/lib/postgresql/data
    networks:
      - proctor-system

networks:
  proctor-system:
    driver: bridge

volumes:
  proctor_db_data: